spring.application.name=Docmind

spring.datasource.url=jdbc:postgresql://localhost:5432/docmind
spring.datasource.username=postgres
spring.datasource.password=Welcome@01
spring.jpa.hibernate.ddl-auto=update

# Local storage path where physical documents will be saved
file.upload-dir=E:/DOC_MIND/filesStorageLocal

#Google Gemini AI Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview

spring.ai.chat.memory.repository.jdbc.initialize-schema=always