spring.application.name=Docmind

spring.datasource.url=jdbc:postgresql://localhost:5432/docmind
spring.datasource.username=postgres
spring.datasource.password=Welcome@01
spring.jpa.hibernate.ddl-auto=update